// <auto-generated />
namespace bit285_lucky_number_database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedanameproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedanameproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201801302319209_Added a name property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
